name: Delete last release

on: workflow_dispatch

jobs:
  removing_release_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get last tag name
        run: |
          json=$(gh api repos/maumuller/react-valisk/releases --jq '.[0].tag_name');
          echo $json;
          echo 'VERSION_PACKAGE='$json >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Version versionNumber
        run: echo "A versão é $VERSION_PACKAGE"

      - name: Delete realease
        run: gh release delete $VERSION_PACKAGE --cleanup-tag -y
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
