name: Generate a new release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  upgrade_package_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org

      - name: Get version package and storage into env variable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 
          versionNumber="$(cat package.json | jq -r '."version"')";
          echo $versionNumber;

      - name: Check Numbers Of Version
        run: |
          firstValue=${versionNumber:0:1};
          secondValue=${versionNumber:2:1};
          thirtyValue=${versionNumber:4:1};

          if [thirtyValue < 9]; then npm version patch; else npm version minor; fi;
          if [secondValue == 9]; then npm version major; fi;

          # lengthVersion=`echo $versionNumber | wc -c`;
          # for((i=0; i<$lengthVersion; i++)); do val=${versionNumber:${i}:1}; if [[ $val =~ [0-9] ]]; then $numbersArray+=($val); fi; done

  salve_package_version:
    runs-on: ubuntu-latest
    needs: upgrade_package_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version package and storage into env variable
        run: |
          versionNumber="$(cat package.json | jq -r '."version"')"
          echo $versionNumber
          echo 'VERSION_PACKAGE='$versionNumber >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Version Package
        run: echo "Versão do pacote - $VERSION_PACKAGE"
