name: Generate a new release with YML

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  salve_package_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: get and salve number
        run: |
          versionNumber="$(cat package.json | jq '."version"')"
          echo $versionNumber
          # echo 'VERSION_PACKAGE='$versionNumber >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

      - name: Test env variable
        run: echo "Versão do pacote - $VERSION_PACKAGE"
