name: Generate a new release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  upgrade_package_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get version package and storage into env variable
        run: |
          versionNumber="$(cat package.json | jq -r '."version"')"
          echo $versionNumber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Numbers Of Version
        run: numbersArray=();
          lengthVersion=`echo $versionNumber | wc -c`;
          for ((i=0; i<$lengthVersion; i++)); do numbersArray[i] = $versionNumber[i]; done;
          echo ${numbersArray[@]}

  salve_package_version:
    runs-on: ubuntu-latest

    needs: upgrade_package_version

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version package and storage into env variable
        run: |
          versionNumber="$(cat package.json | jq -r '."version"')"
          echo $versionNumber
          echo 'VERSION_PACKAGE='$versionNumber >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Version Package
        run: echo "Versão do pacote - $VERSION_PACKAGE"
