name: Unpublish package to NPM

on: workflow_dispatch

jobs:
  unpublish: # JOB
    runs-on: ubuntu-latest
    steps:
      - name: Unpublishing package
        run: npm unpublish --force valisk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM }}
