name: Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  get_package_version:
    runs-on: ubuntu-latest

    outputs:
      version_package: ${{ steps.step_version.outputs.VERSION_PACKAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get package version
        id: step_version
        run: |
          versionNumber="$(cat package.json | jq -r '.version')";
          echo 'VERSION_PACKAGE='$versionNumber >> $GITHUB_OUTPUT

  publish_to_npm:
    runs-on: "ubuntu-latest"
    needs: [get_package_version]

    steps:
      - name: Show last package version
        run: echo "VERSION_PACKAGE="v${{ needs.get_package_version.outputs.version_package }} >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Install Dependences
        run: npm ci

      - name: Publish on NPM
        if: ${{ env.VERSION_PACKAGE != 'v0.0.0' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM }}
